# Generated by Django 4.2.6 on 2023-11-10 13:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment_confirmation_comment_alter_post_text_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_comment_en_us',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_comment_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='headline_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='headline_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контент'),
        ),
    ]
